### ISSUE TITLE
Add the ability to have a TTL for metric names

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#106]
It's nice to be able to automatically purge unused metrics and directories. We should be able to delete unused metric names after 8 days and automatically clean up empty directories.

And idea for that would be to set TTLs in the metadata cache and in the database. To make it work we would have to fetch the ttl from the database when caching it. LMDB (used in the metadata cache) doesn't seem to support TTLs so this might be an issue.

**Comment by dpanth3r** [comment]
I would suggest using a batch cleanup for the initial implementation: just regularly iterate over the whole cache and delete the expired values.

**Comment by iksaif** [comment]
@erebe is fixing this

**Comment by iksaif** [comment]
done
