### ISSUE TITLE
Issues with scaleToSeconds(1) and higher stages

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#133]
Looks like stageToSeconds(1) isn't returning the right values when called on higher stages. Add unit tests to validate that Reader.fetch() return valid answers for metrics with multiple stages.

Also Tweak find_stage_for_ts() to choose the best stage based on both start_time and end_time and check if it would make sense to have overlapping stages.

**Comment by iksaif** [comment]
See also https://github.com/graphite-project/graphite-web/blob/2aee2bceff3f388ebe194e4bedefc60a8a37b3fb/webapp/graphite/render/functions.py#L838

**Comment by natbraun** [comment]
This function actually only works with counter & sums.
