### ISSUE TITLE
graphite_utils.py: __filter_metric() doesn't work with more than one {}

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#154]
We should at least be able to support something like a.{b,c}.{d,e}.{f,g}. The current code is limited to a single list of variants.

**Comment by dpanth3r** [comment]
Pull request in progress :-)

**Comment by iksaif** [comment]
Arg... I made a fix in the train but I failed to push it :/ hopefully we
have something similar

**Comment by dpanth3r** [comment]
Well then, review time!
