### ISSUE TITLE
Handle graphite-like patterns in the drivers

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#169]
Currently the drivers only supports raw wildcards. This doesn't make good use of our indexes and make real-life queries quite long (a lot of them have prefixes before wildcards). We already use the "parent" column for prefix queries, but we could do that for each components.

* On queries such as `foo.bar*` or `foo.*bar*`, the driver should get all the information (bar* and *bar* even if it can't always optimize, on Cassandra one could switch some components to 'CONTAINS' if they want to).
* On queries with square brackets, it might be interesting to expand them *before* querying the driver, and not after.

CC @dpanth3r, @rveznaver

**Comment by dpanth3r** [comment]
* Agreed, we should extract as much as we can on preprocessing, and let the drivers decide on how to use that
* We could start by treating brackets as wildcards (thus benefiting from anything done for the first point); we should keep in mind that the brackets allow for ranges, and those could generate many requests upon expansion (e.g. [0-9] or [a-z]…).

**Comment by iksaif** [comment]
I was thinking that brackets should be expanded only if the number of generated requests stays low (<50?).

**Comment by dpanth3r** [comment]
All right, just wanted to make that explicit :-)
Let's not forget that character choice can also be negated too.
