### ISSUE TITLE
Make tox config more flexible

### ISSUE THREAD

**Issue by dpanth3r** [criteo/biggraphite#179]
We should be able to use tox's `{posargs}` to pass file/class/method selector to avoid running the whole test suite when trying to iterate (I cannot bear the 100s waiting time for everything + Cassandra tests anymore when I just want Cassandra).

**Comment by iksaif** [comment]
Just run normal unit tests in your venv: `python -m unittest discover --failfast --verbose --catch`  you'll be able to select which method you want to run, etc.. `tox` is really only to launch the full test suite.

**Comment by dpanth3r** [comment]
While this is minor, we can have tox run the whole suit AND be able to run named test at the same time, and I believe we should.
