### ISSUE TITLE
Investigate the use of row_cache

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#207]
See http://www.datastax.com/dev/blog/row-caching-in-cassandra-2-1
Most of the queries are the same and run periodically, would make sense to enable the cache.

**Comment by iksaif** [comment]
Tried, the cache gets used, but it's unclear if performances are better

**Comment by dpanth3r** [comment]
Did you notice any meaningful variations in both Cassandra and end-user latencies?

**Comment by iksaif** [comment]
Nop .. but we don't have a lot of reads yet.

**Comment by iksaif** [comment]
We used it for some tables and it seems to help. I'll let administrators enable it when they need it.
