### ISSUE TITLE
Support wildcards inside variants (example: {dns*,ns*})

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#290]

**Comment by dpanth3r** [comment]
Can you please be a bit more specific?
I am guessing that you mean “generate better Cassandra SASI queries for these situations” ?

**Comment by iksaif** [comment]
Currently `foo.{dns*,ns*}` doesn't expand correctly (but `foo.{dns,ns}*` works)

**Comment by iksaif** [comment]
This has been fixed
