### ISSUE TITLE
exceptions in biggraphite.plugins.graphite._merge_cached_points

### ISSUE THREAD

**Issue by NasusOptimus** [criteo/biggraphite#303]
Hello,
i running a render cluster with biggraphite (version: 0.8.11) and i get sometimes exceptions in biggraphite.plugins.graphite._merge_cached_points.

- 1. First exception is a IndexError at line 104.
- 2. Second exception is that type 'float' is not iterable at line 98.

Currently i dont have the original stacktraces anymore because i running biggraphite with this patch:
```
diff --git a/biggraphite/plugins/graphite.py b/biggraphite/plugins/graphite.py
index 64fde85..0f86843 100755
--- a/biggraphite/plugins/graphite.py
+++ b/biggraphite/plugins/graphite.py
@@ -96,12 +96,16 @@ class Reader(BaseReader):
         if not cached_points:
             return points

+        if isinstance(cached_points, dict):
+            cached_points = cached_points.items()
+
         for (timestamp, value) in cached_points:
             step = int(timestamp - (timestamp % stage.precision)) / stage.precision

             index = step - start_step
-            if index < 0 or index > len(points):
+            if index < 0 or index >= len(points):
                 continue
+
             points[index] = value

         return points
```

- **cached_points** is sometimes a dict instead of a list
- **points** index should never be accessed when index is equal to len(points)

**Comment by iksaif** [comment]
To be honest we never really used CarbonLink. The new version of Graphite will have `merge_with_carbonlink` that will do all of that for us (https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/readers/utils.py#L102).

I'd be happy  to merge your patch while waiting for a new release of graphite-web :)

**Comment by NasusOptimus** [comment]
Looking forward than for the next release :)

**Comment by iksaif** [comment]
Should be fixed in master
