### ISSUE TITLE
do I need to hash metrics to writers ?

### ISSUE THREAD

**Issue by lfundaro** [criteo/biggraphite#357]
Hello folks 👋 

when setting up biggraphite-carbon writers, do I need to make sure to use a hashing algorithm for routing metrics ? i.e.: make sure that a writer always sees metric `foo.bar.qux` routed to him and it's the sole writer of it? 

I quickly skimmed to the writer implementation of biggraphite and it seemed that you guys do downsampling and some sort of data aggregation to honor the configured retention policies. This is why I suspect hashing is needed, but please correct me if I'm wrong 😉 

Thank you !

**Comment by iksaif** [comment]
It *should* work even if you don't hash metrics, but if they really move a lot between writer it will waste memory as each writer will need to create the necessary buffers.

In our setup we have relays with `fast-hashing`

**Comment by lfundaro** [comment]
Ok, but if you indeed do downsampling per writer, then hashing is necessary right ? otherwise you might not see the whole set of points to downsample, and worse, they might step on each other's toe to downsample. Or am I missing something here ?

**Comment by iksaif** [comment]
See https://github.com/criteo/biggraphite/blob/master/CASSANDRA_DESIGN.md#data-tables, each writer ads its own id, and the read-path tries to re-conciliate multiple writers. It works well enough with restarts but we never tried without hashing.

**Comment by lfundaro** [comment]
ah ok, that makes it clearer ! thank you !

**Comment by adericbourg** [comment]
Hi @lfundaro 
Do you still have an issue with this?
If yes, can you update with your current status given iksaif's details.
If not, may we close this issue?

**Comment by lfundaro** [comment]
Hi @adericbourg . Thanks for following up. I am closing this issue. 

Cheers.
