### ISSUE TITLE
Cassandra using LUCENE index plugin deployment to nodes

### ISSUE THREAD

**Issue by zerosoul13** [criteo/biggraphite#536]
Hello everyone,

I've been reading about using SASI or [LUCENE](https://github.com/criteo/biggraphite/blob/ac84b6dabe389bae4e7d2c9ccc08e2a0d6fb731d/CASSANDRA_DESIGN.md#lucene ) indexes on Cassandra to improve performance once you are over 10M metrics (our current case). 

For correctness in our setup, I would like to check with you guys if the plugin should be deployed to `data` and `metadata` Cassandra nodes alike when running in split mode or if this would only apply only for `metadata`  nodes. 

Thank in advance!

**Comment by zerosoul13** [comment]
We have it on all nodes, and see a degradation of performance, compared to when not using the split and LUCENE.

**Comment by geobeau** [comment]
We don't use LUCENE internally. We are using SASI and have a patch for it https://github.com/criteo-forks/cassandra/commit/d7f01cb732bb9365b47d868142955cbad70dca03

The change should only be applied to the metadata cluster. The data one don't use secondary indexing
