### ISSUE TITLE
[QUESTION] Biggraphite still alive ? 

### ISSUE THREAD

**Issue by david-guenault** [criteo/biggraphite#539]
Hello, just to know, is this project still active?

thx !

**Comment by iksaif** [comment]
Hello, this project is still actively used at Criteo and there is a team behind it. It doesn't get many updates as it currently seem to feet their need. I'm not longer part of the company though and not longer contributing to it.

As always with free software, feel free to contribute (it's often easier to patch something that to start from scratch) !

**Comment by camathieu** [comment]
Indeed, the project is still alive and managing 120M+ active timeseries @ Criteo.

Some parts are currently transitioning to Golang : https://github.com/criteo-forks/carbon-relay-ng
Some experiments are being done to leverage new tech like Kafka or Elasticsearch.

Feel free to contribute or to reach out would you have any question or suggestion.
