### ISSUE TITLE
tag support in biggraphite

### ISSUE THREAD

**Issue by david-guenault** [criteo/biggraphite#565]
Hello, 
i played with graphite and tag support and (even if documentation is not clear) everything went well. It seems that biggraphite does not work as expected with tag support. 

Can you confirm ?

Regards,
David

**Comment by mycroft** [comment]
Hello @david-guenault, indeed biggraphite does not support tagging at all.
We don't plan to implement it as we're switching to another solution based on Prometheus for our primary monitoring.
