### ISSUE TITLE
Update retention policy on existing data

### ISSUE THREAD

**Issue by zerosoul13** [criteo/biggraphite#575]
Hello BigGraphite team,

Is there an option to update the retention policy on existing data? We've found that a good amount of metrics are falling into an incorrect retention and would like to correct it. I've done research on the bgutil option but came to none.

Is this possible?

example retention **60s;90d** to be updated to **300s:90d**

Thanks!

**Comment by geobeau** [comment]
Hello, we don’t support the operation with the current tooling. 

If it’s just to extend the ttl time of the metric (60s:30d to 60s:90d), you can use Cassandra tools to move data between tables.

If it’s changing the resolution of a table (60s to 300s), it means that you will have to (re)downsample the data, so a new bgutil function will be required.
We won’t have bandwidth to implement it but you can open a PR and we should be able to give some pointers to help you as well
