### ISSUE TITLE
Reduce TTL for existing data

### ISSUE THREAD

**Issue by zerosoul13** [criteo/biggraphite#588]
Hello BigGraphite team,

We would like to reduce the TTL for metrics. The original retention is **300s:30d,900s:2y** and we would like to reduce it to **300s:30d,900s:1y**.

Is this possible or would it fall into the same case as https://github.com/criteo/biggraphite/issues/575?

Thank you

**Comment by geobeau** [comment]
It's not great but you can trick biggraphite. The TTLs are handled by Cassandra, so you can modify the default_time_to_live of the table in question, the retention will still officially be 2y but in practice data will be discarded earlier

**Comment by geobeau** [comment]
@zerosoul13 did it work?

**Comment by zerosoul13** [comment]
@geobeau Thank you for the follow-up. Our team didn't go through with the approach. It sounds safe, but I didn't want to risk any impact on the dataset.

**Comment by geobeau** [comment]
How much data do you have? Another solution is to:
- generate the new table for 1y
- copy data from 2y to 1y (either via spark, sstableloader or a custom script depending on the size) 
- replace resolution in your metric
