### ISSUE TITLE
cli: bgutil repair

### ISSUE THREAD

**Issue by unbrice** [criteo/biggraphite#60]
Metadata can be made inconsistent:
- After a Cassandra-level issue, we can miss some of the parents in the directories table
- After a Cassandra-level issue or after a failed metric creation, we can have empty directories

A tool should fetch metadata and update them.

**Comment by iksaif** [comment]
Should be 'bg fsck' once #77 is done.

**Comment by iksaif** [comment]
1. Local Metadata Cache can contain entries that are out of sync with Cassandra. Evict them from the cache.
2. After a Cassandra-level issue, we can miss some of the parents in the directories table (example: foo.bar exists, but foo doesn't). Create the missing parent directories (possibly have a local cache with lmdb). This is true for directories and metrics (so we need to do a full scan on both).
