### ISSUE TITLE
drivers: reduce write load

### ISSUE THREAD

**Issue by unbrice** [criteo/biggraphite#69]
When we expire datapoints (most writes), we update consecutive points within one row. By using [unlogged batch](http://docs.datastax.com/en/cql/3.1/cql/cql_reference/batch_r.html), we can update all points in one Cassandra update.

We should not however put the different stage level in a batch. Instead we can skip updating retention levels if the value did not change.

**Comment by iksaif** [comment]
http://docs.datastax.com/en/cql/3.1/cql/cql_using/useBatch.html

> Batches are often mistakenly used in an attempt to optimize performance. Unlogged batches require the coordinator to manage inserts, which can place a heavy load on the coordinator node. If other nodes own partition keys, the coordinator node needs to deal with a network hop, resulting in inefficient delivery. Use unlogged batches when making updates to the same partition key.


We still need to reduce the amount of downsampled points being written.

**Comment by iksaif** [comment]
I ended doing that some time ago
