### ISSUE TITLE
Improve _CassandraAccessor.__glob_names performances

### ISSUE THREAD

**Issue by iksaif** [criteo/biggraphite#73]
Looking at current thread pool usage it seems that this kind of read is using most of our CPU.
Looking at http://xf.iksaif.net/bordel/trace it also seems that a single query is doing a lot !

It is yet to be seen if it's fine for listing metrics, but this is clearly the bottleneck when creating them.
- See if we can make this query less expensive.
- Do not use self.glob_directory_names() when we can simply do a select on the primary key.

This is big issue not only when we get a ton of new metric, but also when carbon looses its cache because only the cache is checked (a miss in the cache should probably trigger a read in the DB).

**Comment by unbrice** [comment]
Can you attach the query? Also the trace seems truncated.

If the query is on prefix a select seems like a great optimisation. Also on the (possibly truncated) trace I can only see one of the index being used.

**Comment by iksaif** [comment]
The trace is truncated because it's to big to be easilly collectable with my current setup.
The query was 
`SELECT name FROM "biggraphite_metadata"."directories" WHERE component_0 = 'latency' AND component_1 = 'histogram' AND component_2 = 'le' AND component_3 = '__END__' LIMIT 5001 ALLOW FILTERING;
`

**Comment by iksaif** [comment]
Short term fix, change:

```
        parent_dir = metric.name.rpartition(".")[0]
        if parent_dir and not self.glob_directory_names(parent_dir):
            
```

**Comment by unbrice** [comment]
#74 should remove index from the metric access path

**Comment by iksaif** [comment]
The performances are now good enough.
