### ISSUE TITLE
Why DTCS?

### ISSUE THREAD

**Issue by deniszh** [criteo/biggraphite#79]
Hello!
As far as I understand you still using `DateTieredCompactionStrategy` for timeseries data. But Cassandra 3 already have better alternative - `TimeWindowCompactionStrategy`.
Rational behind it is in https://issues.apache.org/jira/browse/CASSANDRA-9666
[Raintank's metrictank](https://github.com/raintank/metrictank/blob/master/docs/cassandra.md) uses TWCS.

**Comment by iksaif** [comment]
That's avery good point, we were not aware of this compaction strategy. I wasn't able to find a full up-to-date documentation for TimeWindowCompactionStrategy, would you have it ?

Currently DCTS seems to work pretty well for us. We will start doing full imports of our data next week and we could clearly benchmark it.

**Comment by deniszh** [comment]
IIRC docs are only in Jeff's repo - https://github.com/jeffjirsa/twcs
He explaining details in his slides too - http://www.slideshare.net/JeffJirsa1/cassandra-summit-2015-real-world-dtcs-for-operators

**Comment by iksaif** [comment]
I guess we'll try that once we have something stable enough that it makes sense to compare numbers. Thanks !

**Comment by deniszh** [comment]
Will be fixed in https://github.com/criteo/biggraphite/pull/100
